name: 'Test Selenium IDE'

on:
  workflow_dispatch:
    inputs:
      trigger:
        description: 'Trigger the workflow'
        required: true
        default: 'manual'
jobs:
  test:
    permissions:
      actions: read
      checks: read
      contents: write
      deployments: read
      issues: read
      discussions: read
      packages: read
      pages: read
      pull-requests: read
      repository-projects: read
      security-events: read
      statuses: read
    runs-on: windows-latest
    if: github.repository == 'TristanBenoit2/selenium-ide'
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8.11.0
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm -r i
      - name: Build side-runner and selenium-ide
        run: npm run build
      - name: Run all tests
        run: npm run test
      - name: Run selenium tests
        run: npm run test-selenium-windows
